/**
 * Passing the table to another device, and receiving one.
 *
 * The use case is a single, concrete one: the battery of the phone counting
 * life is running out in the middle of the match, and someone at the table has
 * a charged device. The match has to change hands without ending.
 *
 * By CODE, when there is a cloud: the table goes up and a six-letter code
 * shows, which whoever carries on types (or receives in a link). Nobody needs
 * an account. It used to be by file only, and the .json sent over WhatsApp did
 * not open on the receiver's phone - the handoff failed in the middle of the
 * game.
 *
 * The file stays as the offline way out: a table at a friend's house tends to
 * have bad wi-fi, and that is where the code handoff offers the file instead.
 *
 * What travels is ONE table. The backup exporter sends the whole database,
 * and using it here would hand the friend the whole match history of whoever
 * passed it.
 */

import {
  el, clear, icon, openSheet, toast, confirmAction, buzz,
} from '../../ui.js';
import { t } from '../../i18n.js';
import * as store from '../../store.js';
import { isHandedOff } from '../../engine.js';
import { cloudEnabled } from '../../config.js';
import {
  sendTable, peekTable, takeTable, tableStatus, cancelTable,
  codeInText, formatCode,
} from '../../cloud.js';

/** How often the open code asks whether the table has arrived. */
export const STATUS_POLL_MS = 3000;

/**
 * The file name, with the match id.
 *
 * A fixed name turned two tables in the downloads folder into
 * `mesa-hit-easy (1).json`, and then nobody knows which is which - neither the
 * sender nor the receiver. The id is what identifies the match everywhere else
 * in the app.
 *
 * Filtered to what every file system accepts: the id is generated by the app
 * and today only has letters, digits and `_`, but a file with a slash in its
 * name does not save, and finding that out on someone else's phone would be
 * too late. (The `mesa-hit-easy` prefix is what users see; it stays.)
 */
export function tableFileName(match) {
  const id = String((match && match.id) || '')
    .replace(/[^a-zA-Z0-9_-]/g, '')
    .slice(0, 40);
  return 'mesa-hit-easy' + (id ? '-' + id : '') + '.json';
}

/**
 * Hands the file to the system.
 *
 * Tries the native share first, which is the short path: the file goes
 * straight to WhatsApp, AirDrop or whatever the person uses, without going
 * through the downloads folder. Not every browser accepts sharing a FILE -
 * some only accept text - and that is why `canShare` is asked with the file in
 * hand instead of just asking whether `share` exists.
 *
 * The download is the usual way out: it downloads, and the person sends it as
 * they would send any file.
 */
async function deliver(text, name) {
  const blob = new Blob([text], { type: 'application/json' });

  try {
    const file = new File([blob], name, { type: 'application/json' });
    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({ files: [file], title: t('pass.shareTitle') });
      return 'shared';
    }
  } catch (e) {
    // Cancelling the share lands here, and it is not an error: the table stays
    // handed off, and the person can use the button again.
    if (e && e.name === 'AbortError') return 'cancelled';
  }

  const a = el('a', { href: URL.createObjectURL(blob), download: name });
  document.body.append(a);
  a.click();
  setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 0);
  return 'downloaded';
}

/**
 * Passes the table: confirms, uploads, shows the code.
 *
 * The confirmation says what happens to THIS device, not what happens to the
 * table. "It will generate a code" is not the information that matters; "you
 * stop playing here" is.
 *
 * The table only leaves here AFTER it goes up. If the network fails, it stays
 * open on this device, and the screen offers the file, which does not depend
 * on the network.
 *
 * `onPassed` runs as soon as the table leaves here - and the caller switches
 * screens. The code shows after that, on top of the new screen: switching
 * screens closes any open panel, and the code cannot vanish before it is read.
 */
export async function passTable(onPassed) {
  if (!store.getCurrent()) { toast(t('pass.nothing')); return false; }

  const ok = await confirmAction({
    title: t('pass.confirmTitle'),
    message: t(cloudEnabled() ? 'pass.confirmMsgCode' : 'pass.confirmMsg'),
    confirmLabel: t('pass.confirm'),
  });
  if (!ok) return false;

  if (cloudEnabled()) {
    const envelope = store.tableToSend();
    if (!envelope) { toast(t('pass.nothing')); return false; }
    toast(t('pass.uploading'));
    try {
      const code = await sendTable(envelope);
      store.releaseTable(code);
      if (onPassed) onPassed();
      showCode(code);
      return true;
    } catch {
      // No network, or the database still without migration 007: the file
      // solves it.
      const byFile = await confirmAction({
        title: t('pass.offlineTitle'),
        message: t('pass.offlineMsg'),
        confirmLabel: t('pass.sendFile'),
        danger: false,
      });
      if (!byFile) return false;
    }
  }

  return passByFile(onPassed);
}

/** The usual path: stamps and delivers the file. */
async function passByFile(onPassed) {
  // The name comes from the table BEFORE packing: packing stamps it and, after
  // that, `getCurrent()` already returns null - the handed-off table stops
  // being the current one.
  const name = tableFileName(store.getCurrent());

  const text = store.packTable();
  if (!text) { toast(t('pass.nothing')); return false; }

  await deliver(text, name);
  if (onPassed) onPassed();
  toast(t('pass.done'));
  return true;
}

/**
 * The link that opens the app already on receive, with the code filled in.
 * (`?mesa=` is the parameter in links already shared - it stays.)
 */
export function tableLink(code, where = typeof location === 'undefined' ? null : location) {
  const base = where ? where.origin + where.pathname.replace(/index\.html$/, '') : '';
  return base + '?mesa=' + code;
}

/**
 * Sends the code through the conversation.
 *
 * Text, not a file: any phone's WhatsApp opens text. The code AND the link go
 * - the link opens the app already on receive, and the code serves whoever
 * uses the app installed on an iPhone, which does not open links (it opens
 * Safari, which keeps its data apart from the app).
 */
async function shareCode(code) {
  const text = t('pass.shareText', { code: formatCode(code), link: tableLink(code) });
  try {
    if (navigator.share) {
      await navigator.share({ title: t('pass.shareTitle'), text });
      return;
    }
  } catch (e) {
    if (e && e.name === 'AbortError') return;
  }
  copy(text);
}

async function copy(text) {
  try {
    await navigator.clipboard.writeText(text);
    toast(t('pass.copied'));
  } catch {
    toast(text);
  }
}

/**
 * The code, big, and whether the other device has picked it up.
 *
 * It asks the database while the panel is open: "it arrived" is the only thing
 * whoever passed wants to know, and without this they stayed looking at the
 * code without knowing whether they could put the phone away.
 */
export function showCode(code) {
  let timer = null;
  const stop = () => { clearInterval(timer); timer = null; };

  openSheet({
    title: t('pass.codeTitle'),
    subtitle: t('pass.codeSub'),
    onClose: stop,
    build: (pane, close) => {
      const status = el('p', { class: 'table-code-status', text: t('pass.waiting') });

      const ask = async () => {
        let r;
        try { r = await tableStatus(code); } catch { return; }
        if (r !== 'recebida' || !timer) return;
        stop();
        status.textContent = t('pass.arrived');
        status.classList.add('is-done');
        buzz(20);
      };
      timer = setInterval(ask, STATUS_POLL_MS);

      pane.append(
        el('div', { class: 'table-code', 'aria-label': code, text: formatCode(code) }),
        status,
        el('div', { class: 'sheet-actions' }, [
          el('button', { class: 'btn ghost', onClick: () => copy(code) }, [t('pass.copyCode')]),
          el('button', { class: 'btn primary', onClick: () => shareCode(code) }, [
            icon('share'), t('pass.shareCode'),
          ]),
        ]),
        el('button', { class: 'btn ghost block table-code-done', onClick: close }, [t('common.done')]),
      );
    },
  });
}

/** What to say about each file that is no good. */
function fileError(err) {
  const key = {
    unreadable: 'pass.errUnreadable',
    'not-a-table': 'pass.errNotTable',
    'newer-version': 'pass.errNewer',
    'invalid-table': 'pass.errBroken',
  }[err && err.message];
  return t(key || 'pass.errUnreadable');
}

/**
 * Asks whether it may receive, showing the size of the table.
 *
 * Replacing the match open here is irreversible, and nobody confirms what they
 * cannot check. It applies to the file and to the code.
 */
function confirmReceive(match) {
  const count = (match.seats || []).length;
  const open = store.getCurrent();
  return confirmAction({
    title: t('pass.receiveTitle'),
    message: open && !isHandedOff(open)
      ? t('pass.receiveReplace', { n: count })
      : t('pass.receiveMsg', { n: count }),
    confirmLabel: t('pass.receive'),
    danger: Boolean(open && !isHandedOff(open)),
  });
}

/** What to say when the cloud failed. */
function networkError(err) {
  return t(err && err.message === 'offline' ? 'pass.codeOffline' : 'pass.codeServer');
}

/**
 * Receives a table by code.
 *
 * In two steps, like the database: first SEE the table (without consuming the
 * code), confirm with the person, and only then TAKE it. Taking before
 * confirming would burn the code of whoever gave up halfway - and the table
 * would have no owner.
 *
 * With no cloud configured, it goes straight to the file.
 */
export function openReceiveTable(onReceived, initialCode = '') {
  if (!cloudEnabled()) { receiveTableFile(onReceived); return; }

  openSheet({
    title: t('pass.receiveCodeTitle'),
    subtitle: t('pass.receiveCodeSub'),
    build: (pane, close) => {
      const field = el('input', {
        class: 'table-code-field',
        placeholder: 'K7M 2QX',
        autocapitalize: 'characters',
        autocomplete: 'off',
        autocorrect: 'off',
        spellcheck: 'false',
        enterkeyhint: 'go',
        'aria-label': t('pass.receiveCodeTitle'),
      });
      if (initialCode) field.value = formatCode(initialCode);
      const error = el('p', { class: 'table-code-error' });
      const warn = (text) => { error.textContent = text || ''; };

      const receive = el('button', { class: 'btn primary' }, [t('pass.receive')]);
      let busy = false;

      const unlock = () => {
        busy = false;
        receive.disabled = false;
        receive.textContent = t('pass.receive');
      };

      const attempt = async () => {
        if (busy) return;
        const code = codeInText(field.value);
        if (!code) { warn(t('pass.codeInvalid')); return; }
        warn('');
        busy = true;
        receive.disabled = true;
        receive.textContent = t('pass.searching');

        let seen;
        try {
          seen = await peekTable(code);
        } catch (e) {
          unlock();
          warn(networkError(e));
          return;
        }
        if (!seen) { unlock(); warn(t('pass.codeNotFound')); return; }

        let data;
        try {
          data = store.readReceivedTable(seen);
        } catch (e) {
          unlock();
          warn(fileError(e));
          return;
        }

        close();
        if (!await confirmReceive(data.partida)) return;

        let taken;
        try {
          taken = await takeTable(code);
        } catch (e) {
          toast(networkError(e));
          return;
        }
        if (!taken) { toast(t('pass.codeTaken')); return; }

        // Installs what was TAKEN, not what was seen: the taken one is what
        // the database guarantees belongs to this person and nobody else.
        try {
          store.installTable(store.readReceivedTable(taken));
        } catch (e) {
          toast(fileError(e));
          return;
        }
        if (onReceived) onReceived();
      };

      receive.addEventListener('click', attempt);
      field.addEventListener('keydown', (e) => { if (e.key === 'Enter') attempt(); });
      // Pasting the whole message from the chat: the field finds the code in it.
      field.addEventListener('input', () => {
        const found = codeInText(field.value);
        if (found && field.value.length > 7) field.value = formatCode(found);
        warn('');
      });

      pane.append(
        field,
        error,
        el('div', { class: 'sheet-actions' }, [
          el('button', {
            class: 'btn ghost',
            onClick: () => { close(); receiveTableFile(onReceived); },
          }, [t('pass.haveFile')]),
          receive,
        ]),
      );
      if (!initialCode) setTimeout(() => { try { field.focus(); } catch { /* no focus */ } }, 250);
    },
  });
}

/**
 * Receives a table from a file.
 *
 * Reads before installing, and shows whose it is and which turn it is on:
 * replacing the match open here is irreversible, and nobody confirms what they
 * cannot check.
 */
export function receiveTableFile(onReceived) {
  const field = el('input', { type: 'file', accept: '.json,application/json' });
  field.style.display = 'none';

  field.addEventListener('change', async () => {
    const file = field.files && field.files[0];
    if (!file) return;

    let data;
    try {
      data = store.readTable(await file.text());
    } catch (e) {
      toast(fileError(e));
      field.remove();
      return;
    }

    const ok = await confirmReceive(data.partida);
    field.remove();
    if (!ok) return;

    store.installTable(data);
    // The caller takes us to the table. Without this the match was installed
    // and the screen stayed on the home screen - only reloading the page found
    // it, because the initial route is the only one that looks at
    // `getCurrent()` by itself.
    if (onReceived) onReceived();
  });

  document.body.append(field);
  field.click();
}

/**
 * The notice that the table left this device.
 *
 * It sits on the home screen because that is where the person looks again,
 * and it disappears by itself when there is no handed-off table - a permanent
 * notice becomes scenery.
 *
 * Taking back exists for when the handoff did not work out: the file did not
 * arrive, the friend gave up. It is deliberately an action with a
 * confirmation, because two live copies of the same match is exactly what the
 * handoff prevents.
 */
export function handedOffBanner(onRefresh, onTakeBack) {
  // `storedTable` and not `getCurrent`: for the rest of the app the handed-off
  // table does not exist, and this screen is the one that needs to see it to
  // warn and offer taking it back.
  const table = store.storedTable();
  if (!isHandedOff(table)) return null;

  const box = el('div', { class: 'handed-off' });
  const code = table.passadaCodigo || null;
  let arrived = false;

  const paint = () => {
    clear(box);
    const sub = !code ? t('pass.goneSub')
      : t(arrived ? 'pass.goneSubArrived' : 'pass.goneSubCode', { code: formatCode(code) });
    box.append(el('div', { class: 'handed-off-txt' }, [
      el('span', { class: 'menu-label', text: t('pass.goneTitle') }),
      el('span', { class: 'menu-sub', text: sub }),
    ]));
    box.append(el('div', { class: 'handed-off-acts' }, [
      // While nobody took it, the code has to be one tap away: the person
      // closed the panel before sending, or the friend asked again.
      code && !arrived
        ? el('button', { class: 'btn ghost', onClick: () => showCode(code) }, [t('pass.showCode')])
        : null,
      el('button', {
        class: 'btn ghost',
        onClick: async () => {
          const ok = await confirmAction({
            title: t('pass.takeBackTitle'),
            message: t('pass.takeBackMsg'),
            confirmLabel: t('pass.takeBack'),
          });
          if (!ok) return;
          // Handed off by code: cancel it in the cloud before taking back, so
          // the code does not stay valid with the table back here. If the other
          // device already took it, taking back creates two live copies - the
          // person needs to know that before, not after.
          if (code) {
            let r = null;
            try { r = await cancelTable(code); } catch { /* no network: carry on */ }
            if (r === 'recebida') {
              const anyway = await confirmAction({
                title: t('pass.takeBackReceivedTitle'),
                message: t('pass.takeBackReceivedMsg'),
                confirmLabel: t('pass.takeBackAnyway'),
              });
              if (!anyway) return;
            }
          }
          store.takeTableBack();
          // To the table, and not back to the home screen: taking back means
          // "the game goes on here", and whoever takes back wants to keep
          // playing. Stuck on the home screen the person had no way back to
          // the match.
          if (onTakeBack) onTakeBack();
          else if (onRefresh) onRefresh();
        },
      }, [t('pass.takeBack')]),
      el('button', {
        class: 'btn ghost',
        onClick: async () => {
          const ok = await confirmAction({
            title: t('pass.dropTitle'),
            message: t('pass.dropMsg'),
            confirmLabel: t('pass.drop'),
          });
          if (!ok) return;
          store.clearCurrent();
          if (onRefresh) onRefresh();
        },
      }, [t('pass.drop')]),
    ]));
  };

  paint();

  // A single question, when drawing: if the other device already took it, the
  // notice says so and the show-code button disappears. Failing here only
  // leaves the old text.
  if (code && cloudEnabled()) {
    tableStatus(code).then((r) => {
      if (r !== 'recebida') return;
      arrived = true;
      paint();
    }).catch(() => {});
  }

  return box;
}

/** The way in to receive, at the foot of the home screen. */
export function receiveTableButton(onReceived) {
  return el('button', {
    class: 'receive-table',
    onClick: () => openReceiveTable(onReceived),
  }, [icon('download'), t('pass.receiveCta')]);
}

/**
 * The way out to an open match, when the home screen finds one.
 *
 * Normally nobody sees this: the app opens straight on the table when there is
 * a match, and only goes back to the home screen when finishing or discarding.
 * But taking back created a state that did not exist before - home screen with
 * a live match - and getting stuck there was the reported defect. Instead of
 * only fixing that path, the home screen now knows how to offer the way out
 * whenever the state shows up, wherever it comes from.
 */
export function resumeTableBanner(onResume) {
  const table = store.getCurrent();
  if (!table) return null;

  return el('button', {
    class: 'invite-banner',
    onClick: onResume,
  }, [
    el('span', { class: 'invite-banner-n' }, [icon('arrow')]),
    el('span', { class: 'invite-banner-txt' }, [
      el('span', { class: 'menu-label', text: t('pass.resumeTitle') }),
      el('span', { class: 'menu-sub', text: t('pass.resumeSub') }),
    ]),
  ]);
}

/** Explains the feature, for whoever taps without knowing what it is. */
export function openAboutPassing() {
  openSheet({
    title: t('pass.aboutTitle'),
    subtitle: t('pass.aboutSub'),
    build: (pane) => {
      pane.append(el('p', { class: 'account-note', text: t('pass.about1') }));
      pane.append(el('p', { class: 'account-note', text: t('pass.about2') }));
    },
  });
}
